#!/usr/bin/env bash
#This script installs nginx the web server

sudo apt-get -y update
sudo apt-get -y install nginx

echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start