#!/usr/bin/env bash
#This script installs nginx and configures it

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i '24i\    rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
