#!/usr/bin/env bash
#This script installs nginx and configures it for not found page with showin 404 error

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i '24i\    rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/error_404.html
sudo sed -i '46i\ error_page 404 /error_404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
