#!/usr/bin/env bash
#This script installs nginx and configures it

sudo apt-get -y update
sudo apt-get -y install nginx

HOST_NAME=$(hostname)
HEADER="\\\n\tadd_header X-Served-By $HOST_NAME;\n"
FIND=$(grep "X-Served-By" /etc/nginx/sites-available/default)

if [[ -z $FIND ]]; then
	sudo sed -i "24i $HEADER" /etc/nginx/sites-available/default
fi

echo -e "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo sed -i '24i\    rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo sed -i '24i\    rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html
sudo sed -i '46i\ error_page 404 /error_404.html;' /etc/nginx/sites-available/default

sudo service nginx restart