#!/usr/bin/env bash
#This script configure HAproxy on lb-01 server.

#Update packages and instal HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy

#Configure HAProxy
server_conf=\
"
frontend yassmine-attar.tech
	bind *:80
	default_backend web-servers

backend web-servers
	balance roundrobin
	server 447553-web-01 100.25.38.120:80 check
	server 447553-web-02 18.234.168.234:80 check
"
echo "$server_conf" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
#Restart HAProxy service
sudo service haproxy restart
